version: '3'
services:
    webapp:
        image: node:14
        container_name: webapp
        working_dir: /home/node/app
        command: yarn run dev
        volumes:
            - .:/home/node/app
            - /home/node/app/node_module
            - /home/node/app/.next
        ports:
            - 3000:3000
        networks:
            - app
        restart: on-failure
networks:
    app:
        driver: bridge